Execute async option
PrefectHQ/prefect-snowflake pull request #34
Opened 2022-09-12 07:08 UTC by peracto

## Summary

This is a simple change to the existing task to support the Snowflake get/put command.
Snowflake get/put commands don't work when using the Snowflake async_execute method.

NB. This is my first PR - please be kind :)

Apologies ... I'm not sure how to complete the CHANGELOG.md

## Relevant Issue(s)

Add a task to run PUT file commands #8

## Checklist
- [ ] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-snowflake/blob/main/CHANGELOG.md)

2022-09-12 14:53 UTC, desertaxle requested changes
Congrats on your first contribution @peracto! 🎉  Thanks for coming up with a solution to this issue!

Instead of adding an option to the current task to control whether the query is executed synchronously or asynchronously, would you be will to create a new task that executes queries synchronously? We could name that task `snowflake_query_sync` and document that it should be used for PUT commands. A separate synchronous task will allow the two query tasks to evolve independently and will be simpler than if we combined them into one.

2022-09-13 00:12 UTC, ahuang11 commented
I think this closes https://github.com/PrefectHQ/prefect-snowflake/issues/8

2022-09-13 07:54 UTC, peracto commented
Yes, I did consider that. I'll update to add the new task.

2022-09-15 16:27 UTC, ahuang11 requested changes
Thanks so much for contributing!

Depending on the built-in error of using execute_async with put/get, I wonder if we should add a check to see if "put" or "get" is used in `execute_query()` and redirect them to use `execute_query_sync` instead. It could also go into another PR.

2022-09-15 16:27 UTC, ahuang11 commented on README.md
> +For get/put operations use the
```suggestion
To execute `get` and `put` statements, use `snowflake_query_sync`.
```

2022-09-15 16:27 UTC, ahuang11 commented on README.md
> +### Execute get/put into Snowflake stage
```suggestion
### Execute `get` and `put` statements
```

2022-09-15 16:27 UTC, ahuang11 commented on README.md
> +import pandas as pd
```suggestion
```

2022-09-15 16:27 UTC, ahuang11 commented on prefect_snowflake/database.py
> +                params={"id_param": 1}
```suggestion
```

2022-09-15 16:27 UTC, ahuang11 commented on prefect_snowflake/database.py
> +        Query Snowflake table with the ID value parameterized.
```suggestion
        Execute a put statement.
```

2022-09-15 16:27 UTC, ahuang11 commented on prefect_snowflake/database.py
> +        def snowflake_query_flow():
```suggestion
        def snowflake_query_sync_flow():
```

2022-09-16 14:18 UTC, desertaxle approved these changes
LGTM!

2022-09-16 15:58 UTC, ahuang11 approved these changes
Thanks so much! I'm sure this will be very useful to others too!

2022-09-16 15:58 UTC, merged